version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
       - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: